#!/usr/bin/env bash

set -o nounset
set -o errexit


echo "Installing kafka_broker_demoter..."
pip install -e .

echo "Installing test libs..."
pip3 install -r requirements/test_requirements.txt
 
echo "Running Flake8 tests..."
flake8 --ignore=E501,W503 kafka_broker_demoter tests

echo "Running isort check..."
isort --profile black -c kafka_broker_demoter tests


pytest -vv -s -rxs tests
